[location]
postcode = POST CODE <-- with the gap
search_radius_km = 11 <-- the bigger the radius, the slower script will be. 

[alerts]
threshold_drop = 0.1 <-- 0.01p change. You can have this as 1.0 (p)
threshold_rise = 0.1

[irc]
enabled = false
server = irc.vibetalk.net
port = 6667
nick = Trump
channel = #lounge

[display]
fast_update = true
partial_update = true

[discord]
enabled = false
webhook_url = 

[telegram]
enabled = false
bot_token = 
chat_id = 
